# Generated by Django 4.2.14 on 2024-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
